services:
  traefik-3:
    container_name: traefik-3
    image: traefik:latest
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    labels:
      - "traefik.enable=true"
      
      - "traefik.http.routers.traefik-3.rule=PathPrefix(`/traefik-3`)"
      - "traefik.http.routers.traefik-3.entrypoints=web"
      - "traefik.http.services.traefik-3.loadbalancer.server.port=80" 

      # Apply the child traefiks middleware to this container
      - "traefik.http.routers.traefik-3.middlewares=traefik-3-middleware"

      # Define the middleware for this child traefik container. 
      # This needs a unique name (cannot be repeated by other child traefik containers)
      - "traefik.http.middlewares.traefik-3-middleware.stripprefix.prefixes=/traefik-3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
  api-3:
    container_name: api-3
    image: api-image
    labels:
      - "traefik.enable=true"
      
      - "traefik.http.routers.api-3.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.api-3.entrypoints=web"
      - "traefik.http.services.api-3.loadbalancer.server.port=5000"

    networks:
      - proxy

networks: 
  proxy:
    external: true